/*
   Authors: Noam Damari 209280601, Ronel Yust 318434644, Sofi Eliazarov 325025872
   Description: This file contains the model for the calories items for the MongoDB database
*/

// Adding all our dependencies
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Define the schema for the calories collection
const caloriesSchema = new Schema({
    user_id: {
        type: Number,
        // Requires a user id for each calories item.
        required: true 
    },
    year: {
        type: Number,
    },
    month: {
        type: Number,
    },
    day: {
        type: Number,
    },
    id: {
       // Automatically generated by the server
        type: String,
        required: true,
        unique: true
    },
    description: {
        type: String,
        // Requires a description for each calories item.
        required: true,
    },
    category: {
        type: String,
        enum: ["breakfast" , "lunch" , "dinner" , "other"],
        // Requires a category for each calories item.
        required: true
    },
    amount: {
        type: Number,
        // Requires an amount of calories for each calories item.
        required: true,
    }
});

// Create a model named Calories based on the schema
const Calories = mongoose.model('Calories',caloriesSchema);
module.exports = Calories;
